language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
#  - "3.5-dev" # 3.5 development branch
#  - "3.6-dev" # 3.6 development branch
#  - "nightly" # currently points to 3.7-dev
# command to install dependencies
#
before_install:
  - mysql -e 'CREATE DATABASE importio;'

install: "pip install -r requirements.txt"

# command to run tests
script: nosetests

services:
  - mysql
